services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:fc86aef5168ac8513316@sistemas_despesa-facil-db:5432/sistemas?sslmode=disable
      JWT_SECRET: ${JWT_SECRET:-INSERIR_SECRET_AQUI}
      PORT: 3000
      NODE_ENV: production
      FRONTEND_URL: ${FRONTEND_URL:-https://seu-dominio.com}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    depends_on:
      - backend
